/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/11f33038-e6cb-4f85-b3ea-c46d210ad781 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led;
  CloudTemperatureSensor aht_temp;
  int sht_humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Adafruit_AHT10.h> //added by RJ

Adafruit_AHT10 ahtx; //added by RJ
Adafruit_Sensor *ahtx_humidity, *ahtx_temp; //added by RJ

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(14, OUTPUT);//added by RJ

  //added by RJ start
   if (!ahtx.begin()) {
    Serial.println("Failed to find AHT10 chip");
    while (1) {
      delay(10);
    }
  }

  Serial.println("AHT10 Found!");
  ahtx_temp = ahtx.getTemperatureSensor();
  ahtx_temp->printSensorDetails();

  ahtx_humidity = ahtx.getHumiditySensor();
  ahtx_humidity->printSensorDetails();
//added by RJ end
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 

  //added by RJ start
  sensors_event_t humidity;
  sensors_event_t temp;
  ahtx_humidity->getEvent(&humidity);
  ahtx_temp->getEvent(&temp);
  
  aht_temp = temp.temperature;
  sht_humidity = humidity.relative_humidity;
}
//added by RJ end

/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  // Add your code here to act upon Led change
  //added by RJ start
  if (led == true){
    digitalWrite(14, HIGH);
  }else{
    digitalWrite(14, LOW);
  }

  //added by RJ end
}


